### ISSUE TITLE
[Front] Encryption/Decryption for Upload/Download

### ISSUE THREAD

**Issue by its-colby** [autonomys/auto-drive#6]
- encapsulate all non UI logic so that it can be added to Auto SDK
- allow user to set password, use symmetric cipher for decrypt/encrypt, eg AES

Flow: User sets password, password is saved in local storage (and user saves password to his own password manager). Crypto library is used to derive symmetric key from password, AES is used to encrypt, + MAC tag. Encrypted file sent to backend and treated like any other file. When file downloaded on frontend, frontend will attempt to decrypt with saved password from local storage. If incorrect MAC tag or no saved password, it will prompt user to enter password, then attempt decryption. 

For encrypted files, if they are cached on the user's own machine (the client machine), then they will be cached in decrypted form.

The backend should not be aware of any passwords, salted passwords, or distinguish between encrypted and un-encrypted (plaintext) files.

**Comment by clostao** [comment]
There's a problem regarding the download of folder with encrypted files. Currently folders are downloaded as zip files. The issue is that the files in a folder encrypted would be downloaded by the user encrypted. 

I think that the best option is to upload as encrypted zip files the folders that are wanted to be encrypted.
